static const char col_bg[]               = "#1a1b26";
static const char col_dark[]             = "#16161E";
static const char col_dark_1[]           = "#232433";
static const char col_dark_2[]           = "#2a2b3d";
static const char col_dark_3[]           = "#3b3d57";
static const char col_fg[]               = "#a9b1d6";
static const char col_black[]            = "#32344a";
static const char col_br_black[]         = "#444b6a";
static const char col_white[]            = "#FDF6E3";
static const char col_br_white[]         = "#acb0d0";
static const char col_red[]              = "#f7768e";
static const char col_br_red[]           = "#ff7a93";
static const char col_green[]            = "#9ece6a";
static const char col_br_green[]         = "#b9f27c";
static const char col_yellow[]           = "#e0af68";
static const char col_br_yellow[]        = "#ff9e64";
static const char col_blue[]             = "#7aa2f7";
static const char col_br_blue[]          = "#7da6ff";
static const char col_magenta[]          = "#ad8ee6";
static const char col_br_magenta[]       = "#bb9af7";
static const char col_cyan[]             = "#449dab";
static const char col_br_cyan[]          = "#0db9d7";
static const char *colors[][3]           = {
	/*                     fg              bg              border   */
	[SchemeNorm]       = { col_fg,         col_white,         col_bg },         /* \x0b */
	[SchemeSel]        = { col_blue,       col_white,       col_dark_1 },     /* \x0c */
        [SchemeDarker]     = { col_dark,       col_bg,         col_black },      /* \x0d */
        [SchemeRed]        = { col_red,        col_bg,         col_black },      /* \x0e */
        [SchemeGreen]      = { col_green,      col_bg,         col_black },      /* \x0f */
        [SchemeBlue]       = { col_blue,       col_bg,         col_black },      /* \x10 */
        [SchemeCyan]       = { col_cyan,       col_bg,         col_black },      /* \x11 */
        [SchemeMagenta]    = { col_magenta,    col_bg,         col_black },      /* \x12 */
        [SchemeYellow]     = { col_yellow,     col_bg,         col_black },      /* \x13 */
        [SchemeBlack]      = { col_black,      col_bg,         col_black },      /* \x14 */
        [SchemeWhite]      = { col_white,      col_bg,         col_black },      /* \x15 */
        [SchemeBrRed]      = { col_br_red,     col_bg,         col_black },      /* \x16 */
        [SchemeBrGreen]    = { col_br_green,   col_bg,         col_black },      /* \x17 */
        [SchemeBrBlue]     = { col_br_blue,    col_bg,         col_black },      /* \x18 */
        [SchemeBrCyan]     = { col_br_cyan,    col_bg,         col_black },      /* \x19 */
        [SchemeBrMagenta]  = { col_br_magenta, col_bg,         col_black },      /* \x1a */
        [SchemeBrYellow]   = { col_br_yellow,  col_bg,         col_black },      /* \x1b */
        [SchemeBrBlack]    = { col_br_black,   col_bg,         col_black },      /* \x1c */
        [SchemeBrWhite]    = { col_br_white,   col_bg,         col_black },      /* \x1d */
        [SchemeFloat]      = { col_fg,         col_bg,         col_dark_2 },     /* \x1e */
        [SchemeInactive]   = { col_br_black,   col_bg,         col_black },      /* \x1f */
        [SchemeBar]        = { col_fg,         col_bg,         col_bg },
        [SchemeTag]        = { col_white,   col_bg,         col_black },
        [SchemeTag1]       = { col_fg,         col_dark,       col_black },
	[SchemeTag2]       = { col_red,        col_dark,       col_black },
        [SchemeTag3]       = { col_br_yellow,  col_dark,       col_black },
        [SchemeTag4]       = { col_br_blue,    col_dark,       col_black },
        [SchemeTag5]       = { col_br_magenta, col_dark,       col_black },
	[SchemeTag6]       = { col_br_cyan,    col_dark,       col_black },
	[SchemeTag7]       = { col_br_green,   col_dark,       col_black },
	[SchemeTag8]       = { col_yellow,     col_dark,       col_black },
	[SchemeTag9]       = { col_br_red,     col_dark,       col_black },
	[SchemeLayout]     = { col_white,      col_bg,         col_black },
	[SchemeTitle]      = { col_fg,         col_bg,         col_black },
	[SchemeTitleFloat] = { col_br_blue,    col_bg,         col_black },
	[SchemeTitle1]     = { col_fg,         col_bg,         col_black },
	[SchemeTitle2]     = { col_red,        col_bg,         col_black },
        [SchemeTitle3]     = { col_br_yellow,  col_bg,         col_black },
        [SchemeTitle4]     = { col_br_blue,    col_bg,         col_black },
        [SchemeTitle5]     = { col_br_magenta, col_bg,         col_black },
	[SchemeTitle6]     = { col_br_cyan,    col_bg,         col_black },
	[SchemeTitle7]     = { col_br_green,   col_bg,         col_black },
	[SchemeTitle8]     = { col_yellow,     col_bg,         col_black },
	[SchemeTitle9]     = { col_br_red,     col_bg,         col_black },
};
